language: node_js
node_js:
  - "10"
  - "12"
os:
  - linux
matrix:
  fast_finish: true
cache: yarn
env:
  global:
    #Coveralls
    - secure: L6+CiItn4xZQKY9LMgXK73RO0ExykNUqGJ/z9iWGCrBBfHvQeUljWhvcR533+BaTL5wtQ83DxGKP3nFO2p+P+x82WW7IXnmJ4+IfzT9H9OHoDUGo3n9LFBDuRhxQiAMm9vpdS91tOVRGMv/FJwO6UGWfOz67OypkGS6aR2fdbFDH3SmSGksrGgg87uT37XD+Kp6hUucPnWzHdK/pOYzNSzR07eoJJkBy9n3eeZIrPjh9eUL+WoNPi4f9sGFnvnEkUS2nejUdGHxhaaBh9k67d48/l3TZP5zXpnKUC+oJ9vfDVaF01JVXWUphughsNsnmeHwJTejl5J0t/Guv9IWIguukmkXKjK+A3vfpgraI/l4uU3PxxCYMXmKcSjapqaHAevfGcAml2hd0aYYpHQHvKXKATLqp1TJjefFzGThG6v2YaqmQLXzUUymtbvqLsMwMMOW4qti9+dv7ehtQg8bnfBFu8pnRgui1IT9tQaMP+c6QaMn9nXnmdvfhEyJgFYeDUMc2DJRA16oRGSXQGwqzC4v0eeKxjzUURtldKLbv/phsIoSSVcEbD96r144CbqWoLUBmFBJulox9zfMbkWg6qlrvbZPzGWT8oeEz7oQtTVT50f22hbqssgPb7PFhlluBy7bnqhPkhw36JfnJR5vzSCtKDseR2/btDjOoKfytOfk=
    # npmrc
    - secure: RushbjP3DC7XT7UGlg7pm5BbWAT0A8xqdRmV5BrtiNzyKqdaHICzSiZM8USZ+Y2eydWenprMoVrmCQrp/8I6FMcoBG+pZHffbhSPIMTqQDp5q5g6RxDi//mI8X/NLTXDxl1nTY3XQA/mKgYjVqKjDv6oXo8mNNinBIWarkFcV6brybSrC+kW0Ruxp5ca3JBBl51yMhtq13RXmhbIuFnqGFxBLmpNidDtImu8UXHTNXvQFwSRi8fmJrxalYQF0/utHH/V88aBQGCYo2NgMfZXYdKB55HLd7eBknRFTr/ssicxz5NEWP5GYVgVIRn7qvdCJXBCdzfIm2U3nNENGM5nRwZABfn2TKAJjKqMr96uEylQrqfnmXeq/LNFYJ4OJwLDai+1Q1/KQ5wy0D9mLzlADzfHwG7scZ8I5q2npmdQOnf3SMsm0G9UohutNs/7cuwHk9zgvsNHpfOzoVH+gNmPm0URDkATikO84I9/7gLP16dUdSxC6GVP+qjVRWO9H7k7RU+WmWzADz3wnIr/LOFZHM/ihQ5oWxwpltYiq+WaYQU6LvynlF7+JtvodWC5hlqj1buC+JCmOp+fkmyIUzuU7vbOF4tomJnOh3pemO8cmuTBGdMqAbeiImyfrCQmwsLeOK1xHr6Y+g6r26DYaK9jX1AnQeBMbpFsxn0U6ejSfXY=
install: yarn install --ignore-engines 
script: ./scripts/build.sh
before_deploy:
  - npm prune --production
  - tar -czvf jestpact.tar.gz package.json index.d.ts index.js LICENSE README.md 
  - npm run deploy:prepare
deploy:
  - provider: releases
    api_key:
      secure: VzFsJyP9iWCHn6M09u3LmzZLWsQTc+S4rdlKOJRmXR+aAR7InhHkPGu0nzp0dDTKHxYOM4NUNQqOXWRf8S9ArC5koG/xlbqhgmuPGAA/9stNpCEmF36ic8dezJ4EdcKevFv8oBXEIRS4VBUhPFlGnKbGQ7wHQ/sk092xtZ0yRAyo6p85LgaRllpmPJ190DsN8o/Y/lg9x2Gnhl9lXS97EfRyrH+OKy9Em2mDz0GmnSLi90d3xn9THkh3MnLa+db2tzobd1MqMTtpkbRuBnFOgia9XN8K40OJ4K8zA4GNj+eVV9VchjOlQBME+qurgOOnm4nYf2clP1dSvGoVmjg9OOclD6PFKiLX/5UvnHma2T2fmavhc5p4bugTJKRt3LNJOwYsL+fxrQtSTVciXMHFMBRlkktkQP1hkVdahMF9C59IaT5EG6kpgAbZ8dieWG4ltNKeck/8shcdz0iIYubBELGpNxPzYMxgubAqONBki7XFLRJ6jixEUyKWowU2acMJIeHm7o2w3brbS5TJy3LXo3DxIKF+o60h7zpkaF8aeP8ijNONxR0Kes5a6WT9+Ng5whF0gqzzAcU80DLzntCJ6rL8ev39qMaIynTkBRb2X97+UYu4L71xakmfeJgHjNEF9eHJHfF57vXh3vXiX+AQGt1LMUCzc6CSRyOIQDXsZeA=
    file: jestpact.tar.gz
    skip_cleanup: true
    on:
      tags: true
      branch: master
      node: "10"
  - provider: script
    skip_cleanup: true
    script: ./scripts/publish.sh
    on:
      tags: true
      branch: master
      node: "10"
