version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:8.17
      environment:
        ## this enables colors in the output
        TERM: xterm
jobs:
  build:
    <<: *defaults
    steps:
        - checkout
        - restore_cache:
            keys:
            - v4-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v4-deps-{{ .Branch }}-
            - v4-deps-
        - run:
            name: Install project dependencies
            command: | 
                yarn install
        - save_cache:
            key: v4-deps-{{ .Branch }}-{{ checksum "yarn.lock" }}
            paths:
            - ~/.cache/yarn
        - persist_to_workspace:
            root: ~/
            paths:
            - .cache
            - project
            
  compile-test:
    <<: *defaults  
    steps:
        - attach_workspace:
            at: ~/      
        - run:
            name: Lint Source Files
            command: |
                yarn run lint
        - run:
            name: Build Source Files
            command: |
                yarn run build
        - run:
            name: yarn test
            command: yarn run test
        - store_test_results:
            path: ./coverage/junit/unit
        - store_artifacts:
            path: coverage

workflows:
  version: 2
  build-compile-test-publish:
    jobs:
      - build
      - compile-test:
          requires:
            - build